from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / "output"
ASSETS_DIR = PROJECT_ROOT / "assets"

# Webcam
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
CAMERA_FOURCC = "MJPG"
CAMERA_MIN_WIDTH = 960

# ArUco
ARUCO_DICT = "DICT_4X4_50"
MARKER_ID = 0
MARKER_SIZE_CM = 5.0
SMOOTHING_WINDOW = 10

# Detecção de detrito
MIN_CONTOUR_AREA = 500
MAX_CONTOUR_AREA = 500_000
MORPH_KERNEL_SIZE = 5

# MediaPipe — segmentação interativa (Tasks API)
SEGMENTER_MODEL_PATH = ASSETS_DIR / "interactive_segmenter.task"
SEGMENTER_INFERENCE_SCALE = 0.5

# UI
WINDOW_NAME = "Medidor de Detritos"
WINDOW_INITIAL_WIDTH = 960
WINDOW_INITIAL_HEIGHT = 540

# Performance
CAMERA_BUFFER_SIZE = 1
